baseURL = "https://www.thewayIR.com/"
title = "Rebecca Janis"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = false

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
relativeURLs = true

[params.info]
description = "THE WAY I R" 
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon navy.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Rebecca Janis"
startYear = "2018"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
showReadingTime = true
taxonomyCloudShuffle = true
accentColor = "#bdbdbd"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
sidebar = ["about","search","recent_posts", "taxonomy_cloud", "social_menu"]
footer = []

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "rbjanis@gmail.com"
github = "rbjanis"
twitter = "rbjanis5"
linkedin = "rbjanis"
google_scholar = "tW1w9JEAAAAJ&hl"

[params.comments]
enable = false

[params.comments.staticman]
enable = true
apiEndpoint = "https://api.staticman.net/v2/entry"
maxDepth = 2

#[params.comments.staticman.github]
#username = "MunifTanjim"
#repository = "minimo"
#branch = "master"

# Utterances: https://utteranc.es
[params.comments.utterances]
enable = false
issueTerm = "pathname" # pathname / url / title

#[params.comments.utterances.github]
#username = "MunifTanjim"
#repository = "minimo"

[params.search]
client = "" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1

[[menu.main]]
name = "GitHub"
weight = -10
identifier = "repository"
url = "https://github.com/rbjanis?tab=repositories"